#!/usr/bin/env python

# Show latest jive5ab log
import glob
import os
files = glob.glob("/home/oper/jive5ab.logs/jive5ab-jb.out*")
files.sort(key=os.path.getmtime)
print(files)
lastlog = files[-1]
print("Running tail -f of latest logfile " + lastlog + '...')
os.system("tail -f " + lastlog)
